# Generated by Django 5.1.6 on 2025-02-26 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_calorieentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calorieentry',
            name='created_at',
        ),
        migrations.AddField(
            model_name='calorieentry',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calorieentry',
            name='meal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
