# Generated by Django 5.1.6 on 2025-02-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_calorieentry_created_at_calorieentry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CalorieEntry',
        ),
    ]
