# Generated by Django 5.1.6 on 2025-02-28 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_hydrationtracker_recoveryinsights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryinsights',
            name='user',
        ),
        migrations.CreateModel(
            name='HydrationCalorieTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Enter your weight in kg')),
                ('daily_water_requirement', models.FloatField(default=0)),
                ('daily_calorie_requirement', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HydrationTracker',
        ),
        migrations.DeleteModel(
            name='RecoveryInsights',
        ),
    ]
