# Generated by Django 5.1.6 on 2025-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_hydrationcalorietracker_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrationcalorietracker',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hydrationcalorietracker',
            name='health_status',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='hydrationcalorietracker',
            name='height',
            field=models.FloatField(blank=True, help_text='Enter your height in cm', null=True),
        ),
    ]
