# Generated by Django 5.1.6 on 2025-02-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_hydrationcalorietracker_bmi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('process', models.TextField()),
                ('benefits', models.TextField()),
                ('age_group', models.CharField(max_length=50)),
            ],
        ),
    ]
