# Generated by Django 5.1.6 on 2025-03-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_workoutexercise_delete_workout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.AlterField(
            model_name='hydrationcalorietracker',
            name='health_status',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
